# Configuration file for the pingi project
# NOTE: to know more about the fields of the present file, check
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/.

# ---> Main project metadata
[project]
name = "pingi"
version = "0.1.7"
description = "Wrapper around matplotlib, seaborn and ipython for creating highly configurable data science visualizations with minimal code."
authors = [{ name = "Élio Pereira", email = "eliocp@tuta.io" }]

# Keywords (to improve discoverability and the dependencies that are required to install
# the package)
keywords = [
    "data science",
    "matplotlib",
    "seaborn",
    "markdown",
    "html",
    "display",
]

readme = "README.md"
# Licenses' identifiers
# NOTE: Check
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license to know
# more about the license field.
# NOTE: Check https://spdx.org/licenses/ for a list of valid identifiers.
# NOTE: For the case of proprietary licenses `"LicenseRef-Proprietary"` should be used
# (https://packaging.python.org/en/latest/guides/licensing-examples-and-user-scenarios/#i-have-a-private-package-that-won-t-be-distributed).
# NOTE: MIT license: https://spdx.org/licenses/MIT.html
license = "MIT"
# Glob paths to the license files
# NOTE: Check
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-a-license
# to how to create a license file.
# NOTE: For the case of proprietary licenses `"LicenseRef-Proprietary"` should be used
# (https://packaging.python.org/en/latest/guides/licensing-examples-and-user-scenarios/#i-have-a-private-package-that-won-t-be-distributed).
# NOTE: MIT license file: https://choosealicense.com/licenses/mit/
# WARNING: [year] and [fullname] entries in the file must be replaced.
# NOTE: "LICEN[CS]E*" is a glob pattern that matches both "LICENSE" (american english)
# and "LICENCE" (british and commonwealth english) files with additional suffixes.
license-files = ["LICEN[CS]E*"]

# PyPI classifiers
# NOTE: Check https://pypi.org/classifiers/ for a list of valid classifiers.
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Unix",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
    "License :: OSI Approved :: MIT License",
]

# Minimum version of Python that is supported
requires-python = ">=3.13"

# Runtime dependencies (the main dependencies that are required to run the package)
dependencies = ["ipython>=9.15.0", "seaborn>=0.13.2"]

# ---> Additional dependency groups for development
# NOTE: Command `uv sync --group GROUP` will install the dependencies in the group
# `GROUP` besides the runtime ones.
[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "ruff>=0.16.1",
]
docs = [
    "ipykernel>=7.3.0",
    # WARNING: VS Code restart may be required after installing ipywidgets so that the
    # widgets are properly displayed in the notebook.
    "ipywidgets>=8.1.8",
]


# ---> Scripts that can be run from the command line after installing the package
# NOTE: After installation, command `uv run COMMAND` where COMMAND is the key herein
# given to the respective module path and function (COMMAND = "MODULE_PATH:FUNCTION")
# will be available to run the function.
[project.scripts]
# Install latex.
pingi-install-latex = "pingi.cli:install_latex"
# Uninstall latex
pingi-uninstall-latex = "pingi.cli:uninstall_latex"

# ---> URLs associated with the project
# NOTE: Check https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls
# to know more about the URLs field.
[project.urls]
Homepage = "https://github.com/eliocp/pingi"
Repository = "https://github.com/eliocp/pingi"
Issues = "https://github.com/eliocp/pingi/issues"

# ---> Build backend tool
# NOTE: The build backend tool is responsible for creating the distribution package
# (check
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend
# for more details).
# NOTE: Hatchling tool has many benefits compared to the ubiquitous setuptools (check
# https://hatch.pypa.io/1.8/why/)
[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
# Location of the source code of the package to be used by the Hatchling build backend
# NOTE: https://github.com/pypa/hatch/blob/master/docs/config/build.md#packages
packages = ["src/pingi"]


# ---> Development tools' configurations
# ruff configuration
# NOTE: https://github.com/astral-sh/ruff#configuration
[tool.ruff]
# Assume a python version
target-version = "py313"
# Line maximum length
line-length = 88
# Indentation width
indent-width = 4
